package com.brendanddev.learning_path_api.model;

import java.util.Set;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.GenerationType;

/**
 * Represents a user in the app.
 * Each user has a unique id, name, email, and a set of skills they want to learn.
 */
@Entity
public class User {

    /**
     * Primary key for the User entity.
     * Auto generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the user.
     */
    private String name;

    /**
     * The email of the user.
     */
    private String email;

    /**
     * Skills associated with the user. 
     * Has a many-to-many relationship with a Skill entity since users can have multiple skills and skills can belong to multiple users.
     * FetchType.EAGER to load skills whenever the user is fetched.
     */
    @ManyToMany(fetch = FetchType.EAGER)
    private Set<Skill> skills;

    /**
     * Default constructor required by JPA.
     */
    public User() {}

    // Getters and setters for all fields

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set<Skill> getSkills() {
        return skills;
    }

    public void setSkills(Set<Skill> skills) {
        this.skills = skills;
    }

}
