
# ===========================================
# Docker Compose for SpringDock Application
# ===========================================

version: '3.9'

# 
services:

  # Service named 'springdock' - Defines the container the app will run in
  springdock:

  # Service named 'postgres' - Defines the container the database will run in
  postgres: 
    # Specifies the Docker image to use for this service
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}





  